#!/bin/bash
# shellcheck shell=bash
# A wrapper for `docker compose` that prompts for the project if necessary.
# This also functions as a helper script that grabs the project directory
# from the `$DKC_PROJ_DIR` environment variable.

exec docker compose --project-directory "${DKC_PROJ_DIR:-$(dkc-get-proj-dir)}" "$@"
