#!/bin/bash
# shellcheck shell=bash
# A wrapper for `docker compose stop` that loops through the specified projects, or runs for the
# current directory, or prompts for the project if necessary.

exec dkc-loop "$@" -- dkc stop
